let tips = [
  "Track every expense today. You can’t control what you don’t measure.",
  "Pay yourself first—save at least 10% of your income before spending.",
  "Build an emergency fund equal to 6 months of expenses.",
  "Avoid impulse buying. Wait 24 hours before any non-essential purchase.",
  "Cut unused subscriptions. Small leaks sink big ships.",
  "Create a monthly budget and stick to it.",
  "Use cash or UPI for daily expenses to stay aware of spending.",
  "Clear high-interest debt before thinking about investments.",
  "Start a SIP instead of trying to time the market.",
  "Invest in yourself—skills often give the highest return.",
  "Increase your savings rate whenever your income increases.",
  "Avoid lifestyle inflation. Live like you did before the raise.",
  "Keep insurance and investments separate.",
  "Maintain a clear goal for every investment.",
  "Automate savings so you don’t rely on willpower.",
  "Review your bank statements monthly for hidden charges.",
  "Avoid EMIs for depreciating assets.",
  "Keep at least one month of expenses in your savings account.",
  "Diversify investments—don’t put all your money in one place.",
  "Rebalance your portfolio once a year.",
  "Don’t chase quick profits. Wealth is built slowly.",
  "Track your net worth every 6 months.",
  "Have separate accounts for savings and spending.",
  "Learn the difference between needs and wants.",
  "Avoid financial advice driven by social media hype.",
  "Keep a financial journal—note wins and mistakes.",
  "Plan for taxes in advance, not at the last minute.",
  "Review your financial goals annually.",
  "Teach someone else about money—it strengthens your habits.",
  "Consistency beats intensity. Stay disciplined and stay patient."
];

export default tips